<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Post extends Model
{
    use HasFactory;

    protected $fillable = ['id', 'title', 'short_desc', 'alias', 'thumbnail', 'content', 'author_id'];

    public function categories() {
        return $this->belongsToMany(Category::class);
    }

    public function author() {
        return $this->belongsTo(config('admin.database.users_model'), 'author_id');
    }

    public function getThumbnailAttribute() {
        if (empty($this->getAttributes()['thumbnail'])) {
            return '/images/default_thumbnail.jpg';
        }
        return Storage::disk('admin')->url($this->getAttributes()['thumbnail']);
    }

    public function getCreatedDateAttribute() {
        return (new Carbon($this->created_at))->toFormattedDateString();

    }

    protected function bootIfNotBooted()
    {
        parent::bootIfNotBooted(); // TODO: Change the autogenerated stub

        static::creating(function (Post $item) {
            $item->alias = toSlug($item->title);
//            if (empty($item->thumbnail)) $item->thumbnail = config('admin.post.default_thumbnail');
        });
    }
}
